### ISSUE TITLE
New error message with Raspberry Pi5 With LibreELEC

### ISSUE THREAD

**Issue by 03stevensmi** [kFYatek/tweakvec#5] opened 2024-02-02 12:34 UTC
@Alastor27
@kFYatek
Any of you guys could look into this please?
I tried the newest version if tweakvec but now I'm getting this error message:
`python tweakvec.py --preset NTSC
Traceback (most recent call last):
  File "/storage/tweakvec.py", line 867, in <module>
    sys.exit(_main())
             ^^^^^^^
  File "/storage/tweakvec.py", line 854, in _main
    ctx().apply(config, force)
    ^^^^^
  File "/storage/tweakvec.py", line 823, in ctx
    ctx_value = TweakVecContext()
                ^^^^^^^^^^^^^^^^^
  File "/storage/tweakvec.py", line 405, in __init__
    self.vec = VecAccessor(self.memfd, self.mapper, self.pv.model)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/tweakvec.py", line 159, in __init__
    super().__init__(memfd, mapper.map_symbol_address('vec'))
  File "/storage/tweakvec.py", line 105, in __init__
    self.memory = mmap.mmap(memfd, length=length, offset=address)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object cannot be interpreted as an integer
`

**Comment by Alastor27** [comment] 2024-02-02 18:42
Hi @03stevensmi !
I'm not really a maintainer of this project. I just forked it mainly for myself to correct a minor issue caused by python deprecating a library function which was used by this code, and that was a pretty easy fix to do.
I'm afraid, I cannot help you with this one. The original author, @kFYatek is the one, who is qualified for this.
Thank you for your understanding!

**Comment by 03stevensmi** [comment] 2024-02-07 09:52
@kFYatek I have tried it on multiple option systems such as the latest raspian and recalbox!
They all throw me the error mentioned above even when just running the command:
`python3 tweakvec.py`

As I mentioned before, I could get the help to show up before the latest changes but as of now I get that same error message no matter what. 

@kFYatek could you please take a look at this?

**Comment by kFYatek** [comment] 2024-02-07 21:19
Hi @03stevensmi

I think I know what is the problem. On Raspberry Pi 4 and earlier, the composite video encoder is a platform device integrated directly in the SoC. On Raspbery Pi 5, it seems that it is attached to the PCIe bus, and the way the script currently maps memory addresses isn't compatible with this arrangement.

Unfortunately, I don't have access to a Raspberry Pi 5, so even though I can guess a bit based on the devicetrees in the kernel, I cannot really test any solution I come up with.

If you want to help me resolve this problem, please provide a couple of files (please run the commands on a RPi5 with composite output enabled in `config.txt`):

- Please run `tar -czf devicetree.tar.gz -C /sys/firmware/devicetree .` in some writable directory - this should create a `devicetree.tar.gz` file that I'll be able to examine to double-check how the Pi5 devicetree is exposed to userland applications.
- Please also run `sudo dmesg > dmesg.txt`, preferably quite early after freshly booting the Pi - this will create a `dmesg.txt` file that should contain the mapped addresses that I'll be able to check the calculations against.

Please send me those two files and I'll see what I can do in terms of Pi5 support.

But once again, I'd very much advise you to use native support for all various TV norms that is present in modern kernels. There should be no need to use `tweakvec` these days if all you need is switching presets. See the [`enable_tvout` section in the config.txt docs](https://www.raspberrypi.com/documentation/computers/config_txt.html#enable_tvout) for details.

**Comment by 03stevensmi** [comment] 2024-02-08 00:03
> Hi @03stevensmi
> 
> I think I know what is the problem. On Raspberry Pi 4 and earlier, the composite video encoder is a platform device integrated directly in the SoC. On Raspbery Pi 5, it seems that it is attached to the PCIe bus, and the way the script currently maps memory addresses isn't compatible with this arrangement.
> 
> Unfortunately, I don't have access to a Raspberry Pi 5, so even though I can guess a bit based on the devicetrees in the kernel, I cannot really test any solution I come up with.
> 
> If you want to help me resolve this problem, please provide a couple of files (please run the commands on a RPi5 with composite output enabled in `config.txt`):
> 
> * Please run `tar -czf devicetree.tar.gz -C /sys/firmware/devicetree .` in some writable directory - this should create a `devicetree.tar.gz` file that I'll be able to examine to double-check how the Pi5 devicetree is exposed to userland applications.
> * Please also run `sudo dmesg > dmesg.txt`, preferably quite early after freshly booting the Pi - this will create a `dmesg.txt` file that should contain the mapped addresses that I'll be able to check the calculations against.
> 
> Please send me those two files and I'll see what I can do in terms of Pi5 support.
> 
> But once again, I'd very much advise you to use native support for all various TV norms that is present in modern kernels. There should be no need to use `tweakvec` these days if all you need is switching presets. See the [`enable_tvout` section in the config.txt docs](https://www.raspberrypi.com/documentation/computers/config_txt.html#enable_tvout) for details.

I'm on it! I will send you the 2 files.

As for the tvout solution, you do realise that its not working on the pi5 for some reason. 
Only basic USA ntsc and UK pal.

The docs are useless in regards of composite documentation on the pi5.
Apparently its changed to tv_mode= in the cmdline.txt

Anyway, I will send you those 2 files now. :)

**Comment by 03stevensmi** [comment] 2024-02-08 00:10
@kFYatek here are the 2 files:
[devicetree.tar.gz](https://github.com/kFYatek/tweakvec/files/14202873/devicetree.tar.gz)
[dmesg.txt](https://github.com/kFYatek/tweakvec/files/14202874/dmesg.txt)

**Comment by kFYatek** [comment] 2024-02-08 08:52
@03stevensmi Thank you for those files, I just looked at those and it gave me some important details.

A couple of comments and suggestions on the spot:

* The docs I linked mention enabling `dtoverlay=vc4-kms-v3d,composite` and setting e.g. `vc4.tv_mode=PAL60` in `cmdline.txt`, have you tried that?
* If that doesn't work, could you try e.g. `drm-rp1-vec.tv_norm=PAL60` instead, or if that doesn't work, you could also try putting the TV standard on the video mode, i.e. adding something like `video=Composite-1,tv_mode=PAL60` in `cmdline.txt` instead.
* Thanks to your log I realized that the Pi5 uses a completely different driver for its composite output, which suggests to me that it might have a completely different set of registers and thus might not be compatible with `tweakvec` at all.

I'll take a better look at your files and the kernel sources later, but I wouldn't get my hopes up for getting `tweakvec` to work on Pi5 any time soon. I think you definitely have a better chance getting one of the `cmdline.txt` tweaks to work.

**Comment by 03stevensmi** [comment] 2024-02-08 09:04
> @03stevensmi Thank you for those files, I just looked at those and it gave me some important details.
> 
> A couple of comments and suggestions on the spot:
> 
> * The docs I linked mention enabling `dtoverlay=vc4-kms-v3d,composite` and setting e.g. `vc4.tv_mode=PAL60` in `cmdline.txt`, have you tried that?
> * If that doesn't work, could you try e.g. `drm-rp1-vec.tv_norm=PAL60` instead, or if that doesn't work, you could also try putting the TV standard on the video mode, i.e. adding something like `video=Composite-1,tv_mode=PAL60` in `cmdline.txt` instead.
> * Thanks to your log I realized that the Pi5 uses a completely different driver for its composite output, which suggests to me that it might have a completely different set of registers and thus might not be compatible with `tweakvec` at all.
> 
> I'll take a better look at your files and the kernel sources later, but I wouldn't get my hopes up for getting `tweakvec` to work on Pi5 any time soon. I think you definitely have a better chance getting one of the `cmdline.txt` tweaks to work.

Thanks man, I haven't tried drm-rp1-vec. Your the first guy thats mentioned this so thank you for the info.
Ive tried everything (including step 1 & 3) to get tv_mode to work other than basic ntsc-m & pal-I... but nothing. So I really hope there will someday be tweakvec support.

The devs did send me this link:
https://github.com/raspberrypi/linux/pull/5885

**Comment by kFYatek** [comment] 2024-02-08 10:45
@03stevensmi It's not entirely clear from your comment whether `drm-rp1-vec.tv_norm` works, so please get back when you try it :) If it does work, then it would probably be worth it to notify the Raspberry Pi team so that they update the docs.

Like I said, I'll take a look, but I think that if anything, there'd most likely need to be a separate version of `tweakvec` just for Pi5, given that it seems to have a different, incompatible composite encoder with a different set of features.

And for that, I'd need to acquire a Pi5 so that I could play with it and test.

**Comment by 03stevensmi** [comment] 2024-02-08 11:03
> @03stevensmi It's not entirely clear from your comment whether `drm-rp1-vec.tv_norm` works, so please get back when you try it :) If it does work, then it would probably be worth it to notify the Raspberry Pi team so that they update the docs.
> 
> Like I said, I'll take a look, but I think that if anything, there'd most likely need to be a separate version of `tweakvec` just for Pi5, given that it seems to have a different, incompatible composite encoder with a different set of features.
> 
> And for that, I'd need to acquire a Pi5 so that I could play with it and test.

I've tried to notify the devs about updating the docs and they are aware, but they just won't 
For some reason. The GitHub link I posted above shows that the docs need to be updated.
I have no idea what they have done to completely change the way tvnorm is set.

I've tried what you suggested above (apart from the seccond suggestion)
but they don't work. 

I highly doubt though setting `drm-rp1-vec.tv_norm=NTSC-J` will actually do anything
But I hope something works. Or at least someone would say anything regarding what I need to
Set in `cmdline.txt` and `config.txt` to get other TV standards working because the docs are completely
Off regarding the pi5. 
Not sure about the 3+4 but I'd assume there correct in the docs.
My pi3b+ & 4 seems to work fine when using 
`enable_tvout=1
sdtv_mode=1 #NTSC-J 
sdtv_aspect=1  `
&
video=Composite-1:720x480@60ie
dtoverlay=vc4-kms-v3d-pi4,cma-512,composite=1

If its possible, I can help test in anyway I can if you need.

**Comment by kFYatek** [comment] 2024-02-10 18:42
@03stevensmi I have studied the kernel driver for the Raspberry Pi 5 VEC in a little bit more detail. The BCM2712 chip present in the Pi5 no longer contains a composite video encoder - a completely different one has been added as part of the RP1 southbridge chipset, designed in-house by the Raspberry Pi Foundation. This encoder has a completely different register layout, and even a very different function set (it actually combines functions of both the VEC and its corresponding PixelValve from the earlier Broadcom designs).

There is no way that `tweakvec` could ever support Raspberry Pi 5. I will update the model detection code and the README accordingly soon.

That being said, the current kernel driver seems to be fairly complete (if a bit hardcode-ish). The RP1 VEC does not support SECAM but other than that it's actually much more versatile than its Broadcom counterpart. `NTSC`, `NTSC-J`, `NTSC-443`, `PAL`, `PAL-M`, `PAL-N` and `PAL60` are all supported in both interlaced and progressive variants by both hardware and the kernel driver.

What might give you a little trouble is that there are various ways of controlling this setting depending on the kernel version and hardware version.

* Before kernel 5.10, the kernel support for VEC was very incomplete and it was preferred to use firmware-driven mode setting, so `sdtv_mode`, `tvservice` etc.
* Between kernel versions 5.10 and 6.2, the support for VEC (on Raspberry Pi 4 and earlier) got mature, but there was no kernel-wide standard of managing analog TV standards, and each driver handled it on its own. When running one of those kernels:
  * You can use `vc4.tv_norm=` option on the kernel command line (`cmdline.txt`) to choose the standard at boot time **on Raspberry Pi 4 and earlier**
  * The corresponding option **for Raspberry Pi 5**, which uses a different driver, is `drm-rp1-vec.tv_norm=`
  * In runtime, this option can be controlled via the DRM property called `mode` (for both drivers), e.g. under Xorg: `xrandr --output Composite-1 --set mode PAL-M`
  * Both Raspberry Pi drivers have an explicit `PAL60` setting for a 60 Hz mode on PAL TVs (that can handle it)
* Between kernel version 6.3 and 6.5, there is now a standard way of configuring the analog TV standard.
  * The `drm-rp1-vec` driver used on Raspberry Pi 5 **has not been migrated to the new style**, so you should still use old-style (e.g. `drm-rp1-vec.tv_norm=`) settings. However, please read on.
  * At boot time, you can use `video=Composite-1:tv_mode=`  option on the kernel command line (`cmdline.txt`) regardless of the driver (or better yet: `video=Composite-1:720x480i,tv_mode=` / `video=Composite-1:720x576i,tv_mode=` with explicitly specified video mode).
  * At runtime, the new DRM property is called `TV mode` so e.g. under Xorg you can use: `xrandr --output Composite-1 --set "TV mode" PAL-M`
  * There is no explicit `PAL60` mode. To enable PAL60, choose a 720x480i (or similar) video mode and set the standard to PAL, because that's what PAL60 really is (e.g. `video=Composite-1:720x480i,tv_mode=PAL` on the kernel command line - that might not propagate to other apps like Xorg - or `xrandr --output Composite-1 --mode 720x480i --set "TV mode" PAL` in Xorg)
  * The `vc4` driver used on Raspberry Pi 4 and earlier retained compatibility with the old-style settings, although it renames `PAL60` to `PAL-60` (with a dash) for some reason.
* Since kernel version 6.6
  * Nothing changes for Raspberry Pi 4 and earlier
  * For Raspberry Pi 5, a new patch that you mentioned above (https://github.com/raspberrypi/linux/pull/5885) has been merged on February 2nd that migrates it to the new-style settings **and removes the old-style settings**. So when running the bleeding edge newest kernel from the 6.6, 6.7 or 6.8 branch, you can **only** use `video=Composite-1:tv_mode=` or `xrandr --output Composite-1 --set "TV mode"` and none of the legacy settings will work.

So please update your kernel, check its version, and use settings appropriate for that. I hope something will work for you. Good luck!

**Note:** at the moment of writing this, the latest kernel in the Raspberry Pi OS repositories is 6.1.58 (so you should use old-style settings), while running `rpi-update` will get you kernel 6.6.16 (with the aforementioned change included, so you should use new-style settings).

**Note:** when specifying the `video=` mode on the kernel command line, if you want to only specify `tv_mode` without setting the resolution, there needs to be a **colon** between `Composite-1` and `tv_mode`, not a comma like some sources (including my speculations in previous comments) quote.

If I ever acquire a Raspberry Pi 5, then I might write something like `tweakvec` for the new hardware (it seems to be quite powerful, it might be fun!), but it'll need to be a completely new and different piece of software with a different feature set. But there are no immediate plans to do that.

**Comment by kFYatek** [comment] 2024-02-10 21:17
I reverted the "initial support for Raspberry Pi 5" and added a note and guide about kernel features to the README.

As mentioned, there are no immediate plans to support Pi 5 either in this tool or any new one, so I'm closing this issue.

**Closed as completed by kFYatek** 2024-02-10 21:17 UTC

**Comment by 03stevensmi** [comment] 2024-02-11 14:30
@kFYatek my god, thank you so very much.
You have no idea how much you have actually helped me!

I've been trying to get that exact information from anyone one the official rpi forums, discord etc
With literally no one other than a couple of bits here and there on how to change TV standards.

You have actually helped me with the exact information i have been trying to bleed out of Google search
Without any success.

For that,
I want to give you my whole hearted gratitude!
I would have never gotten anywhere without your help.

Thank you.
It really means a lot.
I'm off to finally try out what you suggested.
;D
